TOKEN_JWT = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTkyLjE2OC4xMC4zNzo4MDAwL2FwaS9sb2dpbiIsImlhdCI6MTcxOTUxNjAyMywiZXhwIjoxNzE5NTE5NjIzLCJuYmYiOjE3MTk1MTYwMjMsImp0aSI6IjhURWlHZ2ZQaTFOQkx5UjgiLCJzdWIiOi"
BASE_URL = "https://comercio.munipachacamac.gob.pe"
 